# Generated by Django 6.0.4 on 2026-04-13 18:08

import businesses.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('Cafe', 'Cafe / Coffee Shop'), ('Restaurant', 'Restaurant'), ('Hotel', 'Hotel / Resort'), ('Salon', 'Salon / Spa'), ('Gym', 'Gym / Fitness'), ('Bakery', 'Bakery'), ('Bar', 'Bar / Pub'), ('Clinic', 'Clinic / Healthcare'), ('Retail', 'Retail Shop'), ('Other', 'Other')], default='Restaurant', max_length=50)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('logo_emoji', models.CharField(default='🏪', max_length=10)),
                ('primary_color', models.CharField(default='#6366f1', max_length=7)),
                ('google_place_id', models.CharField(blank=True, max_length=300)),
                ('google_access_token', models.TextField(blank=True)),
                ('google_refresh_token', models.TextField(blank=True)),
                ('auto_send_positive_replies', models.BooleanField(default=True)),
                ('min_rating_for_gift', models.IntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Businesses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('gift_type', models.CharField(choices=[('free_drink', 'Free Drink'), ('free_item', 'Free Item'), ('free_dessert', 'Free Dessert'), ('discount', 'Discount %'), ('store_credit', 'Store Credit')], max_length=20)),
                ('value', models.CharField(help_text='e.g. ₹180 or 20%', max_length=50)),
                ('icon', models.CharField(default='🎁', max_length=10)),
                ('color', models.CharField(choices=[('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('green', 'Green'), ('blue', 'Blue'), ('teal', 'Teal')], default='purple', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('total_issued', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_cards', to='businesses.business')),
            ],
            options={
                'ordering': ['-is_active', 'title'],
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(default='Main Entrance', max_length=100)),
                ('token', models.CharField(default=businesses.models.gen_token, max_length=64, unique=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('scan_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='businesses.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
