# Generated by Django 6.0.4 on 2026-04-13 18:08

import django.db.models.deletion
import reviews.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reviewer_name', models.CharField(blank=True, max_length=100)),
                ('reviewer_email', models.CharField(blank=True, max_length=200)),
                ('rating', models.IntegerField()),
                ('review_text', models.TextField()),
                ('selected_chips', models.JSONField(default=list)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=20)),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('detected_language', models.CharField(default='English', max_length=60)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('posted', 'Posted'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('posted_to_google', models.BooleanField(default=False)),
                ('gift_claim_token', models.CharField(default=reviews.models.gen_token, max_length=64, unique=True)),
                ('gift_claimed', models.BooleanField(default=False)),
                ('gift_claimed_at', models.DateTimeField(blank=True, null=True)),
                ('auto_reply_text', models.TextField(blank=True)),
                ('reply_edited_text', models.TextField(blank=True)),
                ('reply_approved', models.BooleanField(default=False)),
                ('auto_reply_sent', models.BooleanField(default=False)),
                ('auto_reply_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reply_auto_sent_reason', models.CharField(blank=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='businesses.business')),
                ('gift_issued', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='businesses.giftcard')),
                ('qr_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='businesses.qrcode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
